name: Build and Deploy
on:
  push:
    branches: main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
        run: |
          persist-credentials: false

      - name: Install and Build 🔧
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
          REPOSITORY_NAME: kpohiostyle/blog # TODO 
          BRANCH: gh-pages 
          FOLDER: src/.vuepress/dist 
          CLEAN: true 
          SINGLE_COMMIT: true 
